# These are the same prompts used for getting responses and self-explanations.
# The only additions are the instructions to make the model ignore elements
# other than the ones specified in the prompt.

question_template:
  internvl2:
    # No template here, directly ask the question over the image
    llava-bench: ""
    # MMBench contains multiple-choice questions, in this work we apply them in a generation setting
    mmbench: "Provide a concise and descriptive caption for this image."
    # Steer the model to provide only the letter of the option corresponding to the answer
    seed: "Based on the provided image, analyze the given question and choose the most accurate option from the listed alternatives. Your response should consist solely of the letter corresponding to the correct answer (A, B, C, or D), without any additional explanation."
    # The GT answers from this dataset are made of 1 word only. Instruct the model to answer in that way.
    vqav2: "Based on the given image, answer the question using only one word. Provide no additional text or explanation."
  llava-1.6: 
    llava-bench: ""
    mmbench: "Provide a concise and descriptive caption for this image."
    seed: "Based on the provided image, analyze the given question and choose the most accurate option from the listed alternatives. Your response should consist solely of the letter corresponding to the correct answer (A, B, C, or D), without any additional explanation."
    vqav2: "Based on the given image, answer the question using only one word. Provide no additional text or explanation."
  minigpt4: 
    llava-bench: ""
    mmbench: "Provide a concise and descriptive caption for this image."
    seed: "Based on the provided image and question, choose the most accurate answer from the listed alternatives: A, B, C, or D. Only provide the answer, no explanation whatsoever."
    vqav2: "Based on the given image, answer the question using only one word. Provide no additional text or explanation."
  sharegpt4v: 
    llava-bench: ""
    mmbench: "Provide a concise and descriptive caption for this image."
    seed: "Based on the provided image, analyze the given question and choose the most accurate option from the listed alternatives. Your response must consist solely of the answer you believe is correct, without any additional explanation."
    vqav2: "Based on the given image, answer the question using only one word. Provide no additional text or explanation."
constraint_template:
  internvl2: "When answering the question, only consider the following concepts:"
  llava-1.6: "When answering the question, only consider the following concepts:"
  minigpt4: "When answering the question, only consider the following concepts:"
  sharegpt4v: "When answering the question, only consider the following concepts:"