internvl2:
  llava-bench:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  mmbench:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  seed:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  vqav2:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
llava-1.6:
  llava-bench:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  mmbench:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  seed:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  vqav2:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
minigpt4:
  llava-bench:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  mmbench:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  seed:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  vqav2:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
sharegpt4v:
  llava-bench:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  mmbench:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  seed:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
  vqav2:
    ca_data: ca_data.jsonl
    estimates: ce.jsonl
