llava-bench:
  main:
    questions: q.jsonl
    sampled_questions: q_sample.jsonl
mmbench:
  image_scene:
    questions: q_image_scene.jsonl
    sampled_questions: q_image_scene_sample.jsonl
  image_topic:
    questions: q_image_topic.jsonl
    sampled_questions: q_image_topic_sample.jsonl
seed:
  scene_understanding:
    questions: q_scene_understanding.jsonl
    sampled_questions: q_scene_understanding_sample.jsonl
  visual_reasoning:
    questions: q_visual_reasoning.jsonl
    sampled_questions: q_visual_reasoning_sample.jsonl
vqav2:
  how_many_people_are:
    questions: q_how_many_people_are.jsonl
    sampled_questions: q_how_many_people_are_sample.jsonl
  what_is_the_person:
    questions: q_what_is_the_person.jsonl
    sampled_questions: q_what_is_the_person_sample.jsonl
vqav2_holdout:
  is_the_person:    
    questions: holdout/q_is_the_person.jsonl
  is_this_person:
    questions: holdout/q_is_this_person.jsonl