internvl2:
  llava-bench: eval_res.json
  mmbench: eval_res.json
  seed: eval_res.json
  vqav2: eval_res.json
llava-1.6:
  llava-bench: eval_res.json
  mmbench: eval_res.json
  seed: eval_res.json
  vqav2: eval_res.json
sharegpt4v:
  llava-bench: eval_res.json
  mmbench: eval_res.json
  seed: eval_res.json
  vqav2: eval_res.json
qwen2_5_vl:
  llava-bench: eval_res.json
  mmbench: eval_res.json
  seed: eval_res.json
  vqav2: eval_res.json
