internvl2:
  llava-bench: data/really_know/outcomes/internvl2/llava-bench/results_v{}.jsonl
  mmbench: data/really_know/outcomes/internvl2/mmbench/results_v{}.jsonl
  seed: data/really_know/outcomes/internvl2/seed/results_v{}.jsonl
  vqav2: data/really_know/outcomes/internvl2/vqav2/results_v{}.jsonl
llava-1.6:
  llava-bench: data/really_know/outcomes/llava-1.6/llava-bench/results_v{}.jsonl
  mmbench: data/really_know/outcomes/llava-1.6/mmbench/results_v{}.jsonl
  seed: data/really_know/outcomes/llava-1.6/seed/results_v{}.jsonl
  vqav2: data/really_know/outcomes/llava-1.6/vqav2/results_v{}.jsonl
minigpt4:
  llava-bench: data/really_know/outcomes/minigpt4/llava-bench/results_v{}.jsonl
  mmbench: data/really_know/outcomes/minigpt4/mmbench/results_v{}.jsonl
  seed: data/really_know/outcomes/minigpt4/seed/results_v{}.jsonl
  vqav2: data/really_know/outcomes/minigpt4/vqav2/results_v{}.jsonl
sharegpt4v:
  llava-bench: data/really_know/outcomes/sharegpt4v/llava-bench/results_v{}.jsonl
  mmbench: data/really_know/outcomes/sharegpt4v/mmbench/results_v{}.jsonl
  seed: data/really_know/outcomes/sharegpt4v/seed/results_v{}.jsonl
  vqav2: data/really_know/outcomes/sharegpt4v/vqav2/results_v{}.jsonl
