llava-bench:
  main:
    sg_raw: sg_raw.json
    sg_clean: sg_clean.jsonl
    sg_merged: sg_merged.jsonl
    sg_crowd: sg_crowd.jsonl
    val_step: crowd_val.jsonl
    ann_step: crowd_ann.jsonl
    ann_exp: crowd_ann_exp.jsonl
    sk_final: sk_final.jsonl
    sk_exp: sk_exp.jsonl
    crowd_pkl: sg_crowd_nx.pkl
    exp_pkl: sg_exp_nx.pkl
mmbench:
  image_scene:
    sg_raw: sg_raw.json
    sg_clean: sg_clean.jsonl
    sg_merged: sg_merged.jsonl
    sg_crowd: sg_crowd.jsonl
    val_step: crowd_val.jsonl
    ann_step: crowd_ann.jsonl
    ann_exp: crowd_ann_exp.jsonl
    sk_final: sk_final.jsonl
    sk_exp: sk_exp.jsonl
    crowd_pkl: sg_crowd_nx.pkl
    exp_pkl: sg_exp_nx.pkl
  image_topic:
    sg_raw: sg_raw.json
    sg_clean: sg_clean.jsonl
    sg_merged: sg_merged.jsonl
    sg_crowd: sg_crowd.jsonl
    val_step: crowd_val.jsonl
    ann_step: crowd_ann.jsonl
    ann_exp: crowd_ann_exp.jsonl
    sk_final: sk_final.jsonl
    sk_exp: sk_exp.jsonl
    crowd_pkl: sg_crowd_nx.pkl
    exp_pkl: sg_exp_nx.pkl
seed:
  scene_understanding:
    sg_raw: sg_raw.json
    sg_clean: sg_clean.jsonl
    sg_merged: sg_merged.jsonl
    sg_crowd: sg_crowd.jsonl
    val_step: crowd_val.jsonl
    ann_step: crowd_ann.jsonl
    ann_exp: crowd_ann_exp.jsonl
    sk_final: sk_final.jsonl
    sk_exp: sk_exp.jsonl
    crowd_pkl: sg_crowd_nx.pkl
    exp_pkl: sg_exp_nx.pkl
  visual_reasoning:
    sg_raw: sg_raw.json
    sg_clean: sg_clean.jsonl
    sg_merged: sg_merged.jsonl
    sg_crowd: sg_crowd.jsonl
    val_step: crowd_val.jsonl
    ann_step: crowd_ann.jsonl
    ann_exp: crowd_ann_exp.jsonl
    sk_final: sk_final.jsonl
    sk_exp: sk_exp.jsonl
    crowd_pkl: sg_crowd_nx.pkl
    exp_pkl: sg_exp_nx.pkl
vqav2:
  how_many_people_are:
    sg_raw: sg_raw.json
    sg_clean: sg_clean.jsonl
    sg_merged: sg_merged.jsonl
    sg_crowd: sg_crowd.jsonl
    val_step: crowd_val.jsonl
    ann_step: crowd_ann.jsonl
    ann_exp: crowd_ann_exp.jsonl
    sk_final: sk_final.jsonl
    sk_exp: sk_exp.jsonl
    crowd_pkl: sg_crowd_nx.pkl
    exp_pkl: sg_exp_nx.pkl
  what_is_the_person:
    sg_raw: sg_raw.json
    sg_clean: sg_clean.jsonl
    sg_merged: sg_merged.jsonl
    sg_crowd: sg_crowd.jsonl
    val_step: crowd_val.jsonl
    ann_step: crowd_ann.jsonl
    ann_exp: crowd_ann_exp.jsonl
    sk_final: sk_final.jsonl
    sk_exp: sk_exp.jsonl
    crowd_pkl: sg_crowd_nx.pkl
    exp_pkl: sg_exp_nx.pkl
vqav2_holdout:
  is_the_person:
    dir: data/should_know/vqav2/holdout/is_the_person
    sg_raw: scene_graphs/sg_raw.json
    sg_clean: scene_graphs/sg_clean.jsonl
    sg_merged: scene_graphs/sg_merged.jsonl
    sg_crowd: scene_graphs/sg_crowd.jsonl
  is_this_person:
    dir: data/should_know/vqav2/holdout/is_this_person
    sg_raw: scene_graphs/sg_raw.json
    sg_clean: scene_graphs/sg_clean.jsonl
    sg_merged: scene_graphs/sg_merged.jsonl
    sg_crowd: scene_graphs/sg_crowd.jsonl
