import argparse
import copy
import io
import numpy as np
import pandas as pd
import sys
import time
import warnings

from contextlib import redirect_stdout
from dowhy import CausalModel
from econml.inference import BootstrapInference
from pathlib import Path
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LassoCV
from sklearn.ensemble import GradientBoostingRegressor
from word2num import Word2Num

module_path = str(Path("..").resolve())
if module_path not in sys.path:
    sys.path.append(module_path)

import utils.data_io as data_io
import utils.graph_utils as graph_utils

from config_handlers.causal_handler import CausalHandler
from config_handlers.rk_handler import RKHandler

# Disable to see all of the warnings generated by DoWhy + econMl
warnings.filterwarnings("ignore")


def parse_args():
    parser = argparse.ArgumentParser(description="Config for causal analysis.")
    parser.add_argument("--model", required=True)
    parser.add_argument("--dataset", required=True)
    parser.add_argument("--n_repeats", type=int, default=1)
    parser.add_argument(
        "--test_significance",
        type=bool,
        default=False,
        action=argparse.BooleanOptionalAction,
    )
    parser.add_argument(
        "--conf_intervals",
        type=bool,
        default=False,
        action=argparse.BooleanOptionalAction,
    )
    parser.add_argument(
        "--output_stderr",
        type=bool,
        default=False,
        action=argparse.BooleanOptionalAction,
    )
    parser.add_argument(
        "--do_refute", type=bool, default=False, action=argparse.BooleanOptionalAction
    )
    parser.add_argument(
        "--options",
        nargs="+",
        help="override some settings in the used config, the key-value pair "
        "in xxx=yyy format will be merged into config file (deprecate), "
        "change to --cfg-options instead.",
    )
    args = parser.parse_args()
    return args


# Formatting utils
def fix_word_numbers(parser, x):
    res = "<UNK>"
    try:
        res = int(x)
    except ValueError as _:
        # Casting to int failed, silently move on to parser.
        pass
    try:
        res = parser.parse(x)
        if not res:
            res = x  # If parse fails, it is probably a string
        else:
            res = int(res)  # If parse works, make sure an int is returned
    except Exception as e:
        # Parser failed
        print(e)
    finally:
        return res


def make_nx_graphs(resps):
    graphs = {}
    for r in resps:
        print(f"Processing sample id: {r['question_id']}")
        graphs[r["question_id"]] = graph_utils.rk_to_nx(
            r["triple_objs"], return_full=True
        )
        print("-" * 40)
    return graphs


# Causal analysis
def run_causal_inference_DML(
    data,
    nx_graph,
    test_significance=False,
    confidence_intervals=False,
    get_stderr=False,
    do_refute=False,
):
    all_estimates = {}
    all_refutations = {}

    # Prepare data for multinomial logistic regressor
    # responses = data["y"]  # 1-d vector of the responses
    cols_to_skip = ["question_id", "size", "response"]
    cols_to_keep = list(set(data.keys()) - set(cols_to_skip))
    data_for_estimation = data[cols_to_keep]  # n_observations x regressors
    regressors = list(data_for_estimation.drop("y", axis=1).keys())

    for col in regressors:
        print(f"Working on {col}...")

        # Exclude the current 'col' from the variables that can condition the estimates
        effect_modifiers = [r for r in regressors if r != col]

        # effect_modifiers: estimates are separately computed (conditioned)
        # for each value of the effect_modifier.
        model = CausalModel(
            data=data_for_estimation,
            treatment=col,
            outcome="y",
            graph=nx_graph,
            effect_modifiers=effect_modifiers,
        )
        estimand = model.identify_effect(proceed_when_unidentifiable=True)

        # Define method params
        # If less than default n_repeats (5), use only 1 split
        n_split = 2 if len(data) < 5 else 5
        method_params = {
            "init_params": {
                "model_y": GradientBoostingRegressor(),
                "model_t": GradientBoostingRegressor(),
                "model_final": LassoCV(fit_intercept=False, cv=n_split),
                "featurizer": PolynomialFeatures(degree=1, include_bias=False),
            },
            "fit_params": {},
        }
        if test_significance:
            method_params["fit_params"] = {
                "inference": BootstrapInference(n_bootstrap_samples=1, n_jobs=-1)
            }

        # Control and treatment values are correct since we are occluding (removing)
        # elements from images.
        try:
            ce_estimate = model.estimate_effect(
                estimand,
                method_name="backdoor.econml.dml.DML",
                control_value=1,
                treatment_value=0,
                fit_estimator=True,
                method_params=method_params,
            )
        except Exception as e:
            print("Unable to run estimation. Got the following exception:")
            print(e)
            ce_estimate = None
            all_estimates[col] = ce_estimate
            continue

        # Run refutation with Placebo method
        if do_refute:
            print("- Running refutation test for estimate...")
            try:
                all_refutations[col] = model.refute_estimate(
                    estimand,
                    ce_estimate,
                    method_name="placebo_treatment_refuter",
                    show_progress_bar=False,
                    placebo_type="permute",
                )
            except Exception as e:
                print(
                    "Unable to run refutation test of obtained estimate. Got the following exception:"
                )
                print(e)
                all_refutations[col] = None

        # The following calls are is wrapped in a try-except because it might fail
        # when test_significance, confidence_intervals, or get_stderr are True.
        # This is due to incomplete integration between the DoWhy and econML libraries.

        if test_significance:
            print("- Running significance test for estimate...")
            try:
                ce_estimate.test_stat_significance()
            except Exception as e:
                print(
                    "Unable to test significance of obtained estimate. Got the following exception:"
                )
                print(e)

        if confidence_intervals:
            print("- Getting confidence intervals for estimate...")
            try:
                ce_estimate.get_confidence_intervals()
            except Exception as e:
                print(
                    "Unable to get confidence intervals of the obtained estimate. Got the following exception:"
                )
                print(e)

        # Compute standard error for the estimate
        if get_stderr:
            print("- Getting standard error for estimate...")
            try:
                ce_estimate.get_standard_error()
            except Exception as e:
                print(
                    "Unable to get the standard error for the obtained estimate. Got the following exception:"
                )
                print(e)

        all_estimates[col] = ce_estimate

    return all_estimates, all_refutations


def format_estimates(
    estimates,
    refutations=None,
    test_significance=False,
    confidence_intervals=False,
    std_error=False,
):
    formatted_estimates = {}

    for var_name, curr_est in estimates.items():
        # var_name = curr_est._treatment_name[0]
        if var_name not in formatted_estimates:
            formatted_estimates[var_name] = {}

        if curr_est is None:
            continue

        formatted_estimates[var_name] = {
            "estimate": curr_est.value.item(),
            # "estimand_type": curr_est.target_estimand.estimand_type.value,
            # "estimand_expr": curr_est.realized_estimand_expr,
        }

        # Catch the output of the interpret() method
        # f = io.StringIO()
        # with redirect_stdout(f):
        #     curr_est.interpret()
        # formatted_estimates[var_name]["interpretation"] = f.getvalue().strip()

        if test_significance:
            try:
                curr_est.test_stat_significance()
                p_val = curr_est.test_stat_significance()["p_value"]
                if isinstance(p_val, tuple):
                    formatted_estimates[var_name]["p_value"] = list(p_val)
                elif isinstance(p_val, np.floating):
                    formatted_estimates[var_name]["p_value"] = p_val.item()
            except Exception as _:
                formatted_estimates[var_name]["p_value"] = None

        if std_error:
            try:
                formatted_estimates[var_name]["std_error"] = (
                    curr_est.get_standard_error()
                )
            except Exception as _:
                formatted_estimates[var_name]["std_error"] = None

        if confidence_intervals:
            try:
                formatted_estimates[var_name]["conf_intervals"] = (
                    curr_est.get_confidence_intervals()
                )
            except Exception as _:
                formatted_estimates[var_name]["conf_intervals"] = None

        if refutations:
            refute_data = refutations[var_name]
            if refute_data:
                p_val = refute_data.refutation_result["p_value"]
                formatted_estimates[var_name]["refute_test"] = {
                    "is_stat_significant": refute_data.refutation_result[
                        "is_statistically_significant"
                    ].item(),
                }
                if isinstance(p_val, tuple):
                    formatted_estimates[var_name]["refute_test"]["p_value"] = list(
                        p_val
                    )
                elif isinstance(p_val, np.floating):
                    formatted_estimates[var_name]["refute_test"]["p_value"] = (
                        p_val.item()
                    )
            else:
                formatted_estimates[var_name]["refute_test"] = {}

    return formatted_estimates


if __name__ == "__main__":
    t1 = time.time()

    """ Setup """
    # Parse arguments
    args = parse_args()
    MODEL = args.model
    DATASET = args.dataset
    N_REPEATS = args.n_repeats
    TEST_SIGNIFICANCE = args.test_significance
    CONF_INTERVALS = args.conf_intervals
    OUTPUT_STDERR = args.output_stderr
    DO_REFUTE = args.do_refute

    if TEST_SIGNIFICANCE or CONF_INTERVALS or OUTPUT_STDERR:
        print(
            "WARNING: The integration of DoWhy and econML is incomplete. "
            "Computations for testing significance, retrieving confidence "
            "intervals, and standard error for the obtained estimate might fail."
        )

    # Load data handlers
    rk_hdl = RKHandler()
    rk_hdl.set_curr_model(MODEL)
    rk_hdl.set_curr_ds(DATASET)
    causal_hdl = CausalHandler()
    causal_hdl.set_curr_ds(DATASET)
    causal_hdl.set_curr_model(MODEL)

    # Load model responses
    base_dir = Path(__file__).parent.parent
    resps = data_io.load_jsonl(base_dir.joinpath(rk_hdl.get_rk_final_path()))
    counter_resps = data_io.load_jsonl(
        base_dir.joinpath(causal_hdl.get_counter_resps_path())
    )

    print("=" * 60)
    print(f"Processing data for {MODEL} + {DATASET}...")
    """ Preparing data """
    resps_ids = set([q["question_id"] for q in resps])
    dict_counter_resp = {
        q_idx: next(r["response"] for r in counter_resps if r["question_id"] == q_idx)
        for q_idx in resps_ids
    }

    # Merge initial and counterfactual responses
    all_resps = copy.deepcopy(counter_resps)
    for q_idx in resps_ids:
        og_resp = next((r for r in resps if r["question_id"] == q_idx), None)
        if og_resp:
            all_resps.append(
                {
                    "question_id": og_resp["question_id"],
                    "size": 0,
                    "occluded": [],
                    "response": og_resp["response"],
                }
            )
        else:
            print(f"We have an issue with question {q_idx}.")

    # Prepare dataframes for causal analysis
    df = pd.DataFrame(all_resps)
    df.drop(["path"], axis=1, inplace=True)
    df["response"] = df["response"].apply(lambda x: x.lower())

    # Create mapping between questions and the biggest size of constraints.
    max_triplets = {
        q_idx: max([int(q["size"]) for q in all_resps if q["question_id"] == q_idx])
        for q_idx in resps_ids
    }
    # This is done to extract an actual list of concepts, not any other PD objects.
    dict_concepts = {
        q_idx: df[(df["question_id"] == q_idx) & (df["size"] == max_triplets[q_idx])][
            "occluded"
        ].iloc[0]
        for q_idx in max_triplets
    }

    # Resolve numerical answers given as words (e.g., "three")
    w2n = Word2Num()
    df["response"] = df["response"].apply(lambda x: fix_word_numbers(w2n, x))

    # Add column 'y' representing the answer
    # - If response is numeric, just use that
    # - If response is text, create lookup for the results of that question
    lookup_y = {}
    for idx, row in df.iterrows():
        q_idx = row["question_id"]
        if q_idx not in lookup_y:
            lookup_y[q_idx] = {}

        try:
            y = pd.to_numeric(row["response"])
            lookup_y[q_idx][row["response"]] = y
        except Exception as _:
            # Get all rows with same question ID
            curr_q = df[df["question_id"] == q_idx]
            # Create dict entry with list of unique responses
            lookup_y[q_idx] = {v: k for k, v in enumerate(curr_q["response"].unique())}
            y = lookup_y[q_idx][row["response"]]
        finally:
            df.loc[idx, "y"] = y

    """
    Create dictionary of dataframes -- 'df_dict'
    - Dictionary with question_ids as keys for which we have valid RKs
    - Each entry in the dictionary is a dataframe with
        - The original response (no occlusion; size_treatment=0)
        - A bunch of rows with the counterfactual responses (combinations of concepts)
        - A series of binary columns matching 1:1 the concepts present or occluded
    """
    # Make dictionary of dataframes w.r.t. question id
    df_dict = {q_idx: df[df["question_id"] == q_idx] for q_idx in dict_counter_resp}

    # Making binary columns indicating whether a concept was occluded or not.
    # By default, all concepts are present (1). Then, we zero out the ones occluded.
    # Note: each data sample has a different amount of concepts 'attached' to it.
    for q_idx in df_dict:
        for concept in dict_concepts[q_idx]:
            df_dict[q_idx][concept] = 1
    for q_idx in df_dict:
        for id, row in df_dict[q_idx].iterrows():
            curr_concepts = row["occluded"]
            for c in curr_concepts:
                df_dict[q_idx].loc[id, c] = 0
        df_dict[q_idx].drop(["occluded"], axis=1, inplace=True)

    """ Causal Analysis """
    # First, we create the NX graphs based on the data contained from 'resps'.
    # This is done so that we can create the '.dot' string required by 'dowhy'.
    rk_graphs = make_nx_graphs(resps)
    img_ids = list(rk_graphs.keys())
    print(f"Loaded {len(rk_graphs)} samples.")
    print(f"Duplicate ids: {set([x for x in img_ids if img_ids.count(x) > 1])}")

    # Add to each graph a node corresponding to the outcome variable 'y'
    for rk in rk_graphs.values():
        rk.add_node("y", label="response")

        for node in list(rk.nodes()):
            if node == "y":
                continue
            rk.add_edge(node, "y")

    # Run causal analysis -- unlike the main runner, save information locally
    causal_out_path = Path("median_estimates", MODEL, DATASET, "ce.jsonl")
    data_io.make_dir(causal_out_path.parent)
    print(f"Saving estimates to: {str(causal_out_path)}")

    # Load data currently available
    if causal_out_path.exists():
        old_data = data_io.load_jsonl(causal_out_path)
        old_ids = set([od["question_id"] for od in old_data])
    else:
        print("First run.")
        old_ids = []

    for q_idx, rk_data in rk_graphs.items():
        if q_idx in old_ids:
            print(f"Already processed id {q_idx}. Moving to next one.")
            continue

        print("=" * 60)
        print(f">> Working with question # {q_idx} -- Samples: {len(df_dict[q_idx])}")
        curr_rk = rk_data.copy()
        curr_df = df_dict[q_idx]

        out_data = {"question_id": q_idx, "splits": []}

        # Repeat multiple times
        for repeat_idx in range(N_REPEATS):
            print(f"## Running repeat n. {repeat_idx + 1} ##")
            # Compute causal effects
            estimates, refutations = run_causal_inference_DML(
                curr_df,
                curr_rk,
                test_significance=TEST_SIGNIFICANCE,
                confidence_intervals=CONF_INTERVALS,
                get_stderr=OUTPUT_STDERR,
                do_refute=DO_REFUTE,
            )

            # Format and save results of causal analysis
            out_data["splits"].append(
                format_estimates(
                    estimates,
                    refutations=refutations,
                    test_significance=TEST_SIGNIFICANCE,
                    confidence_intervals=CONF_INTERVALS,
                    std_error=OUTPUT_STDERR,
                )
            )

        data_io.append_to_jsonl([out_data], causal_out_path)

    print(f"Total runtime for ({MODEL}, {DATASET}): {time.time() - t1:.2f}s.")
    print("=" * 30)
